language: node_js
node_js:
- 'stable'
- '5'
- '0.10'
- '0.11'
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: HHcfnZhDayj/pPuimQ3zegPCIUYUsc5B3ChuC3s+8S0TXNc36Xw3EPW6+2iMcZmmJPwwevPboiPux5ZW1k7m+cZUUDIK/c39ksjs2xnbnCk9cI0/asYJgjPv/HsiIJSeByMwvuUNgvoWfSgnZ68sbYD21KOW+Io4IRMWLIZNg5M=
  on:
    tags: true
    all_branches: true
    repo: bendrucker/emit-then
